### ISSUE TITLE
Should price at T0 be pythsensus_price_deque[0]

### ISSUE THREAD

**Issue by guibescos** [TrebuchetNetwork/pyth_cip_simulator#1]
In the code, you append the new prices at the right of the deque, therefore I think the oldest price is at index 0 and not -1.

https://github.com/TrebuchetNetwork/pyth_cip_simulator/blob/9cea303496f4a1cb7fe924bbd2940b1c822aafac/trebuchet_validator.py#L97

**Comment by architehc** [comment]
Ser, that is an eye of an eagle there! 👍
